APP_URL= https://performance.develop.farmtoplateapps.io/
LoginPage =https://performance.develop.farmtoplateapps.io/login
HomePageTitle = Farm2Plate
 Gmail_URL =https://accounts.google.com/
 emailfield = farmtoplatef2p@paramountsoft.net
 passwordfield = Admin1234
